apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sit
resources:
- ../../base

patches:
- path: custom-env.yaml
- path: replicas-rollout.yaml
secretGenerator:
- literals:
  - db-password=123456
  name: sl-demo-app
  type: Opaque
images:
- name: docker.m.daocloud.io/library/nginx
  newName: nginx
  newTag: 3.4.5
