# 2.app-config-ConfigMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # 键值对的形式
  name: zhangsan
  mode: production

  # 文件形式
  config.json: |
    {
      "database": {
        "host": "localhost",
        "port": 5432,
        "user": "root",
        "password": "123456"
      }
    }
