apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl-demo-app
  namespace: default
  labels:
    app: sl-demo-app
spec:
  template:
    spec:
      containers:
      - name: sl-demo-app # 该名称要与 base 目录中的 deployment.yaml 中的容器名称保持一致
        env:
        - name: ENV_VAR
          value: "Value from PROD kustomization"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sl-demo-app
              key: db.password